--Relatório Educação e Saúde
SELECT ALU.NOME,
	ALU.DATANASCIMENTO,
	ALU.ID,
	DENG.DATADENGUE
FROM TB_ALUNO ALU
JOIN TB_DENGUE DENG ON ALU.NOME LIKE DENG.NOME
WHERE DENG.DATADENGUE IS NOT NULL
GROUP BY ALU.NOME,
	ALU.DATANASCIMENTO,
	ALU.ID,
	DENG.DATADENGUE