--Relatório Saúde e Mobilidade
SELECT ONI.NOME,
	ONI.DATANASCIMENTO,
	DENG.DATADENGUE,
	ONI.LINHASONIBUS
FROM tb_dengue deng
JOIN tb_busologo oni ON DENG.NOME LIKE ONI.NOME
WHERE DENG.DATADENGUE IS NOT NULL AND ONI.LINHASONIBUS IS NOT NULL
GROUP BY ONI.NOME,
	ONI.DATANASCIMENTO,
	ONI.LINHASONIBUS,
	DENG.DATADENGUE