--Relatório Saúde, Mobilidade e Educação
SELECT ALU.NOME,
	ALU.DATANASCIMENTO,
	DENG.DATADENGUE,
	ONI.LINHASONIBUS
FROM tb_aluno alu
JOIN tb_dengue deng ON deng.nome LIKE alu.nome
JOIN tb_busologo oni ON ONI.NOME LIKE ALU.NOME
WHERE DENG.DATADENGUE IS NOT NULL AND ONI.LINHASONIBUS IS NOT NULL
GROUP BY ALU.NOME,
	ALU.DATANASCIMENTO,
	ONI.LINHASONIBUS,
	DENG.DATADENGUE